require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/category_purchases", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CategoryPurchase. As you add validations to CategoryPurchase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CategoryPurchase.create! valid_attributes
      get category_purchases_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      category_purchase = CategoryPurchase.create! valid_attributes
      get category_purchase_url(category_purchase)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_category_purchase_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      category_purchase = CategoryPurchase.create! valid_attributes
      get edit_category_purchase_url(category_purchase)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CategoryPurchase" do
        expect {
          post category_purchases_url, params: { category_purchase: valid_attributes }
        }.to change(CategoryPurchase, :count).by(1)
      end

      it "redirects to the created category_purchase" do
        post category_purchases_url, params: { category_purchase: valid_attributes }
        expect(response).to redirect_to(category_purchase_url(CategoryPurchase.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CategoryPurchase" do
        expect {
          post category_purchases_url, params: { category_purchase: invalid_attributes }
        }.to change(CategoryPurchase, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post category_purchases_url, params: { category_purchase: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested category_purchase" do
        category_purchase = CategoryPurchase.create! valid_attributes
        patch category_purchase_url(category_purchase), params: { category_purchase: new_attributes }
        category_purchase.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the category_purchase" do
        category_purchase = CategoryPurchase.create! valid_attributes
        patch category_purchase_url(category_purchase), params: { category_purchase: new_attributes }
        category_purchase.reload
        expect(response).to redirect_to(category_purchase_url(category_purchase))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        category_purchase = CategoryPurchase.create! valid_attributes
        patch category_purchase_url(category_purchase), params: { category_purchase: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested category_purchase" do
      category_purchase = CategoryPurchase.create! valid_attributes
      expect {
        delete category_purchase_url(category_purchase)
      }.to change(CategoryPurchase, :count).by(-1)
    end

    it "redirects to the category_purchases list" do
      category_purchase = CategoryPurchase.create! valid_attributes
      delete category_purchase_url(category_purchase)
      expect(response).to redirect_to(category_purchases_url)
    end
  end
end
